from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any

from .contract import CONTRACT_SCHEMA, ThreeDeftBlocked, ensure_ready, parse_contract, validate_contract_template
from .layout import dralgo_model_dir_for_template
from .wolfram_source import format_multiple_perform_drsoft_message, perform_drsoft_calls


GENERATED_DRALGO_SCRIPT_NAME = "generated_3deft_dralgo_marked.m"


@dataclass(frozen=True)
class DRalgoScriptResult:
    output_path: Path
    capture_labels: tuple[str, ...]


def generate_marked_dralgo_script(
    template_path: str | Path,
    *,
    output_path: str | Path | None = None,
) -> DRalgoScriptResult:
    """Generate a Wolfram wrapper around a reviewed user-supplied DRalgo file."""

    template_path = Path(template_path)
    markdown = template_path.read_text(encoding="utf-8")
    report = validate_contract_template(markdown)
    if report.contract.get("schema") != CONTRACT_SCHEMA:
        raise ThreeDeftBlocked(f"Expected a 3DEFT contract with schema {CONTRACT_SCHEMA}.")
    ensure_ready(report, for_dralgo_run=True)

    contract = parse_contract(markdown)
    runner = contract.get("runner", {})
    construction_source = _norm(runner.get("dralgo_construction_source"))
    if construction_source != "reviewed_source_file":
        raise ThreeDeftBlocked("3DEFT now requires runner.dralgo_construction_source=reviewed_source_file.")

    labels_and_calls = _capture_calls(contract)
    if not labels_and_calls:
        raise ThreeDeftBlocked("No DRalgo capture calls were requested in the contract runner policy.")

    source = _required_path(runner.get("dralgo_program_path"), base_dir=template_path.parent)
    source_text = source.read_text(encoding="utf-8", errors="replace")
    soft_calls = perform_drsoft_calls(source_text)
    if len(soft_calls) > 1:
        raise ThreeDeftBlocked(format_multiple_perform_drsoft_message(soft_calls, source_label=str(source)))

    target = Path(output_path) if output_path else dralgo_model_dir_for_template(template_path) / GENERATED_DRALGO_SCRIPT_NAME
    target.parent.mkdir(parents=True, exist_ok=True)
    script = _render_wrapper_script(source, labels_and_calls)
    target.write_text(script, encoding="utf-8")
    return DRalgoScriptResult(output_path=target, capture_labels=tuple(label for label, _call in labels_and_calls))


def _capture_calls(contract: dict[str, Any]) -> list[tuple[str, str]]:
    runner = contract.get("runner", {})
    rg = contract.get("rg_matching", {})
    soft_ready = _soft_matching_ready(contract)
    calls: list[tuple[str, str]] = []
    if _as_bool(runner.get("capture_print_scalar_rep_positions")):
        calls.append(("PrintScalarRepPositions", "PrintScalarRepPositions[]"))
    if _as_bool(runner.get("capture_print_couplings")):
        calls.append(("PrintCouplings", "PrintCouplings[]"))
        for order in _matching_orders(rg.get("hard_matching_order")):
            calls.append((f"PrintScalarMass_{order}", f'PrintScalarMass["{order}"]'))
            calls.append((f"PrintDebyeMass_{order}", f'PrintDebyeMass["{order}"]'))
        calls.append(("PrintTemporalScalarCouplings", "PrintTemporalScalarCouplings[]"))
        if soft_ready:
            calls.append(("PrintCouplingsUS", "PrintCouplingsUS[]"))
            for order in _matching_orders(rg.get("soft_matching_order")):
                calls.append((f"PrintScalarMassUS_{order}", f'PrintScalarMassUS["{order}"]'))
    if soft_ready and _as_bool(runner.get("capture_print_effective_potential")):
        for order in _matching_orders(rg.get("effective_potential_order")):
            calls.append((f"PrintEffectivePotential_{order}", f'PrintEffectivePotential["{order}"]'))
    if soft_ready and _as_bool(runner.get("capture_pressure")):
        for order in _matching_orders(rg.get("pressure_order")):
            calls.append((f"PrintPressureUS_{order}", f'PrintPressureUS["{order}"]'))
    if _as_bool(runner.get("capture_beta_functions")):
        calls.append(("BetaFunctions4D", "BetaFunctions4D[]"))
        if soft_ready:
            calls.append(("BetaFunctions3DS", "BetaFunctions3DS[]"))
            calls.append(("BetaFunctions3DUS", "BetaFunctions3DUS[]"))
    return calls


def _render_wrapper_script(source: Path, calls: list[tuple[str, str]]) -> str:
    source_text = _wolfram_string(str(source))
    rendered_calls = "\n".join(f'ptagentCapture["{label}", HoldForm[{call}]];' for label, call in calls)
    return f"""(* Generated by PTagent 3DEFT. This is only a wrapper; the physics model lives in the reviewed source file. *)
ptagentSourceFile = {source_text};
If[!FileExistsQ[ptagentSourceFile],
  Print["PTAGENT_DRALGO_SOURCE_MISSING: " <> ptagentSourceFile];
  Exit[92]
];
SetDirectory[DirectoryName[ptagentSourceFile]];

{_capture_function_header()}
Get[ptagentSourceFile];
{rendered_calls}
"""


def _capture_function_header() -> str:
    return """ClearAll[ptagentCapture];
ptagentCapture[label_String, held_HoldForm] := Module[{result, reaped, printed},
  Print["<<<PTAGENT_BEGIN:" <> label <> ">>>"];
  reaped = Reap[
    result = Block[
      {Print = Function[Null, Sow[ToString[InputForm[Unevaluated[Slot[1]]], PageWidth -> Infinity]], HoldAll]},
      Quiet[Check[ReleaseHold[held], $Failed]]
    ]
  ];
  printed = If[Length[reaped[[2]]] > 0, Flatten[reaped[[2]]], {}];
  If[Length[printed] > 0,
    Scan[Print, printed],
    Print[ToString[InputForm[result], PageWidth -> Infinity]]
  ];
  Print["<<<PTAGENT_END:" <> label <> ">>>"];
  result
];
"""


def _soft_matching_ready(contract: dict[str, Any]) -> bool:
    commands = [
        str(row.get("command", "")).strip()
        for row in contract.get("eft_stages", [])
        if str(row.get("command", "")).strip().startswith("PerformDRsoft")
    ]
    if not commands or any(_has_unresolved_token(command) for command in commands):
        return False
    scalar_map = contract.get("scalar_index_map", [])
    if not scalar_map:
        return False
    return not any(
        _missing(row.get("scalar_index"))
        or _missing(row.get("field_component"))
        or _missing(row.get("parent_multiplet"))
        or _missing(row.get("integrated_out"))
        for row in scalar_map
    )


def _norm(value: Any) -> str:
    return str(value or "").strip().casefold()


def _missing(value: Any) -> bool:
    normalized = _norm(value)
    return not normalized or normalized.startswith("ask_user") or normalized in {"todo", "tbd", "unknown"}


def _has_unresolved_token(value: Any) -> bool:
    return "ASK_USER" in str(value or "") or _missing(value)


def _wolfram_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _required_path(value: Any, *, base_dir: Path) -> Path:
    raw = str(value or "").strip().strip("`")
    if not raw or raw.casefold().startswith("ask_user"):
        raise ThreeDeftBlocked("DRalgo wrapper generation requires runner.dralgo_program_path.")
    path = Path(raw)
    if not path.is_absolute():
        path = base_dir / path
    path = path.resolve()
    if not path.exists():
        raise ThreeDeftBlocked(f"reviewed DRalgo source file does not exist: {path}")
    return path


def _as_bool(value: Any) -> bool:
    return str(value).strip().casefold() in {"true", "yes", "1", "reviewed", "approved"}


def _order(value: Any) -> str:
    raw = str(value or "").strip().strip('"').upper()
    return raw if raw in {"LO", "NLO", "NNLO"} else ""


def _matching_orders(value: Any) -> tuple[str, ...]:
    order = _order(value)
    if order == "LO":
        return ("LO",)
    if order == "NLO":
        return ("LO", "NLO")
    if order == "NNLO":
        return ("LO", "NLO", "NNLO")
    return ()


__all__ = ["DRalgoScriptResult", "GENERATED_DRALGO_SCRIPT_NAME", "generate_marked_dralgo_script"]
